<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Schema::create('medical_colleges', function (Blueprint $table) {
        //     $table->id();
        //     $table->string('arabic_name')->nullable();
        //     $table->string('english_name')->nullable();
        //     $table->timestamps();
        // });

        // $arabic_data = [
        //     'كلية طب القصر العيني',
        //     'كلية طب جامعة حلوان',
        //     'كلية الطب بجامعة الإسكندرية',
        //     'كلية الطب بجامعة عين شمس',
        //     'كلية طب جامعة أسيوط',
        //     'كلية طب جامعة المنصورة',
        //     'كليات طب جامعة الأزهر',
        //     'كلية طب جامعة الفيوم',
        //     'كلية طب جامعة المنيا',
        //     'كلية طب جامعة بنها',
        //     'كلية طب جامعة بني سويف',
        //     'كلية طب جامعة كفر الشيخ',
        //     'كلية طب جامعة المنوفية',
        //     'كلية طب جامعة جنوب الوادي',
        //     'كلية طب جامعة قناة السويس',
        //     'كلية طب جامعة طنطا',
        //     'كلية طب جامعة الزقازيق',
        //     'كلية طب جامعة سوهاج',
        //     'كلية طب جامعة بورسعيد',
        //     'كلية طب جامعة أسوان',
        //     'كلية طب جامعة دمياط',
        //     'كلية طب جامعة السويس',
        //     'كلية طب القوات المسلحة',
        //     'كلية طب جامعة الوادي الجديد ',
        //     'كلية الطب جامعة الأقصر',
        //     'كلية طب جامعة 6 أكتوبر (O6U)',
        //     'كلية طب جامعة مصر للعلوم والتكنولوجيا (MUST)',
        //     'جامعة نيو جيزة (NGU)',
        //     'كليه طب جامعة النهضة (NUB)',
        //     'كلية طب جامعة بدر بالقاهرة (BUC)',
        //     'كليه طب الجامعة الحديثة (MTI)',
        //     'كلية طب جامعة الدلتا (Delta)',
        //     'كلية طب جامعة الجلالة (Gu)',
        //     'كلية طب جامعة الملك سلمان (KSIU)',
        //     'كلية طب جامعة ميريت (MUE)',
        //     'كلية العلاج الطبيعي (جامعة القاهرة)',
        //     'كلية العلاج الطبيعي (جامعة بني سويف)',
        //     'كلية العلاج الطبيعي (جامعة كفر الشيخ)',
        //     'كلية العلاج الطبيعي (جامعة جنوب الوادي)',
        //     'كلية العلاج الطبيعي (جامعة بنها)',
        //     'كلية العلاج الطبيعي (جامعة السويس)',
        //     'كلية العلاج الطبيعي (جامعة بورسعيد)',
        //     'كلية العلاج الطبيعي (جامعة 6 أكتوبر)',
        //     'كلية العلاج الطبيعي (جامعة سيناء)',
        //     'كلية العلاج الطبيعي (جامعة الأهرام الكندية)',
        //     'كلية العلاج الطبيعي (الجامعة الحديثة)',
        //     'كلية العلاج الطبيعي (جامعة الدلتا)',
        //     'كلية العلاج الطبيعي (جامعة هليوبوليس)',
        //     'كلية العلاج الطبيعي (جامعة حورس)',
        //     'كلية العلاج الطبيعي (جامعة بدر)',
        //     'كلية العلاج الطبيعي (جامعة فاروس)',
        //     'كلية العلاج الطبيعي (الجامعة المصرية الصينية)',
        //     'كلية العلاج الطبيعي (جامعة النهضة)',
        //     'كلية العلاج الطبيعي (جامعة ميريت)',
        //     'كلية العلاج الطبيعي (جامعة دراية)',
        //     'كلية العلاج الطبيعي (جامعة مصر للعلوم و التكنولوجيا)',
        //     'كلية العلاج الطبيعي (جامعة سفنكس)',
        //     'كلية العلاج الطبيعي (جامعة مايو)',
        //     'كلية العلاج الطبيعي (جامعة هيرتفوردشاير)',
        //     'كلية العلاج الطبيعي (جامعة الجلالة)',
        //     'كلية العلاج الطبيعي (جامعة سفنكس)',
        //     'كلية العلاج الطبيعي (جامعة السلام)',
        //     'كلية طب الأسنان جامعة عين شمس',
        //     'كلية طب الأسنان جامعة الأزهر بالقاهرة (بنين)',
        //     'كلية طب الأسنان جامعة الأزهر بأسيوط (بنين)',
        //     'كلية طب الأسنان جامعة الأزهر بالقاهرة (بنات)',
        //     'كلية طب الأسنان جامعة الإسكندرية',
        //     'كلية طب الأسنان جامعة أسيوط',
        //     'كلية طب الأسنان جامعة القاهرة',
        //     'كلية طب الأسنان جامعة المنصورة',
        //     'كلية طب الأسنان جامعة قناة السويس',
        //     'كلية طب الأسنان جامعة طنطا',
        //     'كلية طب الأسنان جامعة كفر الشيخ',
        //     'كلية طب الأسنان جامعة المنيا',
        //     'كلية طب الأسنان جامعة الفيوم',
        //     'كلية طب الاسنان جامعة بني سويف',
        //     'كلية طب الاسنان جامعة الزقازيق',
        //     'كلية طب الاسنان جامعة جنوب الوادي',
        //     'كلية طب الاسنان جامعة سوهاج',
        //     'كلية طب الاسنان جامعة أسوان',
        //     'كلية طب الاسنان جامعة المنوفية',
        //     'كلية طب الأسنان جامعة 6 أكتوبر (O6U)',
        //     'كلية طب الأسنان بجامعة المستقبل (FUE)',
        //     'كلية طب الأسنان بجامعة أكتوبر للعلوم الحديثة والآداب(MSA)',
        //     'كلية طب الأسنان جامعة سيناء',
        //     'كلية طب الأسنان جامعة مصر للعلوم والتكنولوجيا (MUST)',
        //     'كلية طب الأسنان جامعة مصر الدولية (MIU)',
        //     'كلية طب الأسنان الجامعة الحديثة للتكنولوجيا والمعلومات (MTI)',
        //     'كلية طب الأسنان جامعة فاروس بالإسكندرية',
        //     'كلية طب الأسنان الجامعة البريطانية في مصر (BUE)',
        //     'كلية طب الاسنان جامعة سفنكس',
        //     'كلية طب الأسنان جامعة الدلتا',
        //     'كلية طب الأسنان جامعة النهضة',
        //     'كلية طب الأسنان جامعة بدر',
        //     'كلية طب الأسنان الجامعة الروسية',
        //     'كلية طب الأسنان الجامعة الحديثة',
        //     'كلية طب الأسنان جامعة حورس',
        //     'كلية طب الأسنان جامعة الاهرام الكندية',
        //     'كلية طب الاسنان جامعة الجيزة الجديدة',
        //     'كلية طب الفم والأسنان جامعة دراية',

        // ];

        // $data = [
        //     'Kasr Al-Aini Faculty of Medicine',
        //     'Faculty of Medicine, Helwan University',
        //     'Faculty of Medicine, Alexandria University',
        //     'Faculty of Medicine, Ain Shams University',
        //     'Assiut University Faculty of Medicine',
        //     'Faculty of Medicine, Mansoura University',
        //     'Faculties of Medicine, Al-Azhar University',
        //     'Fayoum University Faculty of Medicine',
        //     'Faculty of Medicine, Minya University',
        //     'Faculty of Medicine, Benha University',
        //     'Faculty of Medicine, Beni Suef University',
        //     'Faculty of Medicine, Kafrelsheikh University',
        //     'Faculty of Medicine, Menoufia University',
        //     'Faculty of Medicine, South Valley University',
        //     'Faculty of Medicine, Suez Canal University',
        //     'Faculty of Medicine, Tanta University',
        //     'Faculty of Medicine, Zagazig University',
        //     'Sohag University Faculty of Medicine',
        //     'Faculty of Medicine, Port Said University',
        //     'Aswan University Faculty of Medicine',
        //     'Faculty of Medicine, Damietta University',
        //     'Faculty of Medicine, Suez University',
        //     'College of Armed Forces Medicine',
        //     'Faculty of Medicine, New Valley University',
        //     'Faculty of Medicine, Luxor University',
        //     'Faculty of Medicine, October 6 University (O6U)',
        //     'Faculty of Medicine, Misr University of Science and Technology (MUST)',
        //     'New Giza University (NGU)',
        //     'Nahda University Faculty of Medicine (NUB)',
        //     'Badr University Faculty of Medicine in Cairo (BUC)',
        //     'Modern University Faculty of Medicine (MTI)',
        //     'Faculty of Medicine, Delta University (Delta)',
        //     'Faculty of Medicine, Galala University (GU)',
        //     'King Salman University College of Medicine (KSIU)',
        //     'Merritt University School of Medicine (MUE)',
        //     'Faculty of Physical Therapy (Cairo University)',
        //     'Faculty of Physical Therapy (Beni Suef University)',
        //     'Faculty of Physical Therapy (Kafr El-Sheikh University)',
        //     'Faculty of Physical Therapy (South Valley University)',
        //     'Faculty of Physical Therapy (Benha University)',
        //     'Faculty of Physical Therapy (Suez University)',
        //     'Faculty of Physical Therapy (Port Said University)',
        //     'Faculty of Physical Therapy (6th of October University)',
        //     'Faculty of Physical Therapy (Sinai University)',
        //     'Faculty of Physical Therapy (Al-Ahram Canadian University)',
        //     'Faculty of Physical Therapy (Modern University)',
        //     'Faculty of Physical Therapy (Delta University)',
        //     'Faculty of Physical Therapy (Heliopolis University)',
        //     'Faculty of Physical Therapy (Horus University)',
        //     'College of Physical Therapy (Badr University)',
        //     'Faculty of Physiotherapy (Pharos University)',
        //     'Faculty of Physical Therapy (Egyptian Chinese University)',
        //     'Faculty of Physical Therapy (Nahda University)',
        //     'College of Physical Therapy (Merritt University)',
        //     'College of Physical Therapy (Derayah University)',
        //     'Faculty of Physical Therapy (Misr University of Science and Technology)',
        //     'Faculty of Physical Therapy (Sphinx University)',
        //     'College of Physiotherapy (University of Mayo)',
        //     'School of Physiotherapy (University of Hertfordshire)',
        //     'Faculty of Physical Therapy (Galala University)',
        //     'Faculty of Physical Therapy (Sphinx University)',
        //     'Faculty of Physical Therapy (Al-Salam University)',
        //     'Faculty of Dentistry, Ain Shams University',
        //     'Faculty of Dentistry, Al-Azhar University, Cairo (Boys)',
        //     'Faculty of Dentistry, Al-Azhar University, Assiut (Boys)',
        //     'Faculty of Dentistry, Al-Azhar University in Cairo (Girls)',
        //     'Faculty of Dentistry, Alexandria University',
        //     'Faculty of Dentistry, Assiut University',
        //     'Faculty of Dentistry, Cairo University',
        //     'Faculty of Dentistry, Mansoura University',
        //     'Faculty of Dentistry, Suez Canal University',
        //     'Faculty of Dentistry, Tanta University',
        //     'Faculty of Dentistry, Kafrelsheikh University',
        //     'Faculty of Dentistry, Minya University',
        //     'Faculty of Dentistry, Fayoum University',
        //     'Faculty of Dentistry, Beni Suef University',
        //     'Faculty of Dentistry, Zagazig University',
        //     'Faculty of Dentistry, South Valley University',
        //     'Faculty of Dentistry, Sohag University',
        //     'Faculty of Dentistry, Aswan University',
        //     'Faculty of Dentistry, Menoufia University',
        //     'Faculty of Dentistry, October 6 University (O6U)',
        //     'Faculty of Dentistry at Future University (FUE)',
        //     'Faculty of Dentistry at October University of Modern Sciences and Arts (MSA)',
        //     'Faculty of Dentistry, Sinai University',
        //     'Faculty of Dentistry, Misr University of Science and Technology (MUST)',
        //     'Faculty of Dentistry, Misr International University (MIU)',
        //     'Faculty of Dentistry, Modern University of Technology and Information (MTI)',
        //     'Faculty of Dentistry, Pharos University in Alexandria',
        //     'Faculty of Dentistry, British University in Egypt (BUE)',
        //     'Faculty of Dentistry, Sphinx University',
        //     'Faculty of Dentistry, Delta University',
        //     'Faculty of Dentistry, Nahda University',
        //     'College of Dentistry, Badr University',
        //     'Russian University Faculty of Dentistry',
        //     'Modern University College of Dentistry',
        //     'Faculty of Dentistry, Horus University',
        //     'Faculty of Dentistry, Al-Ahram Canadian University',
        //     'Faculty of Dentistry, New Giza University',
        //     'Faculty of Oral and Dental Medicine, Dirayah University',
        // ];

        // foreach ($arabic_data as $index => $arabic_college) {
        //     DB::table('medical_colleges')->insert([
        //         'arabic_name' => $arabic_college,
        //         'english_name' => $data[$index],
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ]);
        // }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //Schema::dropIfExists('medical_colleges');
    }
};
